# Generated by Django 3.1.2 on 2020-11-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=4)),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=5)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('nuptk', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('agama', models.CharField(max_length=255)),
                ('bergabung', models.CharField(max_length=255)),
                ('madrasah_id', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('rombel', models.CharField(max_length=10)),
                ('tgl_lahir', models.DateField()),
                ('agama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('nama_ayah', models.CharField(max_length=255)),
                ('nama_ibu', models.CharField(max_length=255)),
                ('pekerjaan_ayah', models.CharField(max_length=255)),
                ('pekerjaan_ibu', models.CharField(max_length=255)),
                ('alamat_ortu', models.CharField(max_length=255)),
                ('nama_wali', models.CharField(max_length=255)),
                ('pekerjaan_wali', models.CharField(max_length=255)),
                ('alamat_wali', models.CharField(max_length=255)),
                ('ajaran', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('bergabung', models.CharField(max_length=255)),
                ('kelas_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='school.grade')),
            ],
            options={
                'verbose_name_plural': 'student',
                'db_table': 'student',
            },
        ),
    ]
